#!/usr/bin/python
 
import sys, time

from server import main

from daemon import Daemon
class AirstreamDaemon(Daemon):
    def run(self):
        main(argv=["--quiet"])

if __name__ == "__main__":
    daemon = AirstreamDaemon('/tmp/airstreamd.pid')
    daemonArg = sys.argv[-1]

    if daemonArg in ["start","stop","restart", "foreground"]:
        if 'start' == daemonArg:
            daemon.start()
        elif 'stop' == daemonArg:
            daemon.stop()
        elif 'restart' == daemonArg:
            daemon.restart()
        elif 'foreground' == daemonArg: # for debugging with stdout
            daemon.run()
        else:
            print "Unknown command"
            sys.exit(2)
        sys.exit(0)
    else:
        print "usage: %s start|stop|restart" % sys.argv[0]
        sys.exit(2)

